<#
.SYNOPSIS
    Assemble the backup demo assets into git-ignored outputs/demo-backup/.

.DESCRIPTION
    Copies material that ALREADY EXISTS and is already recorded - real generated
    decals from the Prototype 5 Phase A runs, the UI and deck screenshots, the
    clean-clone captures, and the manifests behind the numbers quoted on stage.

    IT CREATES NOTHING. Every asset is a copy of a tracked or recorded artifact,
    which is why the destination is git-ignored: committing it would duplicate
    evidence the repository already holds. If a source file is missing this
    script says so and continues, so the manifest always reflects what is
    actually there rather than what was hoped for.

    It runs no generation and touches no GPU.

.EXAMPLE
    .\scripts\build-demo-backup.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$dest = Join-Path $repoRoot 'outputs\demo-backup'

$sets = @(
    @{ Name = 'decals';           From = 'outputs\prototype-5';                          Filter = 'P5__*.png' },
    @{ Name = 'screenshots-ui';   From = 'docs\evidence\prototype-5\screenshots\ui';      Filter = '*.jpg' },
    @{ Name = 'screenshots-deck'; From = 'docs\evidence\prototype-5\screenshots';         Filter = '*.jpg' },
    @{ Name = 'screenshots-clone';From = 'docs\evidence\M8\clean-clone\screenshots';      Filter = '*.jpg' },
    @{ Name = 'records';          From = 'docs\evidence\prototype-5';                     Filter = '*.jsonl' }
)

if (Test-Path $dest) { Remove-Item -Recurse -Force $dest }
New-Item -ItemType Directory -Force -Path $dest | Out-Null

Write-Host ""
Write-Host "Assembling backup demo assets into outputs\demo-backup\" -ForegroundColor Cyan
Write-Host ""

$lines = @(
    "# Backup demo assets - manifest",
    "",
    "Generated by scripts/build-demo-backup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm').",
    "",
    "Every file is a COPY of an artifact already tracked or already recorded in this",
    "repository. Nothing here was created for the demo, and nothing here is fabricated.",
    "The destination is git-ignored precisely because it duplicates existing evidence.",
    ""
)

$total = 0
$missing = 0

foreach ($set in $sets) {
    $source = Join-Path $repoRoot $set.From
    $target = Join-Path $dest $set.Name

    if (-not (Test-Path $source)) {
        Write-Host ("MISS  {0,-20} source not found: {1}" -f $set.Name, $set.From) -ForegroundColor Yellow
        $lines += "## $($set.Name)", "", "**SOURCE MISSING:** ``$($set.From)``", ""
        $missing++
        continue
    }

    $files = Get-ChildItem -Path $source -Filter $set.Filter -File -ErrorAction SilentlyContinue
    if (-not $files) {
        Write-Host ("MISS  {0,-20} no files matching {1}" -f $set.Name, $set.Filter) -ForegroundColor Yellow
        $lines += "## $($set.Name)", "", "**NO MATCHING FILES** in ``$($set.From)``", ""
        $missing++
        continue
    }

    New-Item -ItemType Directory -Force -Path $target | Out-Null
    $lines += "## $($set.Name)", "", "Source: ``$($set.From)``", "", "| file | bytes | sha256 |", "|---|---:|---|"

    foreach ($file in $files) {
        Copy-Item $file.FullName -Destination $target -Force
        $hash = (Get-FileHash $file.FullName -Algorithm SHA256).Hash.ToLower()
        # ASCII only. PowerShell 5.1 reads a .ps1 without a BOM as ANSI, so a
        # literal ellipsis here comes out of the file as mojibake.
        $lines += ("| ``{0}`` | {1} | ``{2}...`` |" -f $file.Name, $file.Length, $hash.Substring(0, 16))
        $total++
    }
    $lines += ""

    Write-Host ("OK    {0,-20} {1} file(s)" -f $set.Name, $files.Count) -ForegroundColor Green
}

$lines += "---", "", "**$total file(s) copied.**"
if ($missing -gt 0) { $lines += "", "**$missing source set(s) were missing** - see above. The plan degrades to the sets that exist." }

$manifestPath = Join-Path $repoRoot 'docs\presentation\demo-backup-manifest.md'
$lines | Set-Content -Path $manifestPath -Encoding utf8

Write-Host ""
Write-Host "$total file(s) copied to outputs\demo-backup\" -ForegroundColor Green
Write-Host "Manifest written to docs\presentation\demo-backup-manifest.md"
if ($missing -gt 0) {
    Write-Host "$missing source set(s) missing - the manifest records which." -ForegroundColor Yellow
}
Write-Host ""
exit 0
